/////////////////////////////////////////////////////////////////////////////
//  Copyright (C) 2002-2024 UltraVNC Team Members. All Rights Reserved.
//  Copyright (C) 2004 Martin Scharpf, B. Braun Melsungen AG. All Rights Reserved.
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation; either version 2 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
//  USA.
//
//  If the source code for the program is not available from the place from
//  which you received this file, check
//  https://uvnc.com/
//
////////////////////////////////////////////////////////////////////////////


/* versioninfo.h: Defines 
	STR_COMPANYNAME, 
    STR_FILEVERSION,
	STR_PRODUCTVERSION,
	STR_COPYRIGHT,
	STR_SPECIALBUILD,
	INT_FILEVERSION,
	INT_PRODUCTVERSION */

#ifndef ULTRAVNC_VERSIONINFO_H
#define ULTRAVNC_VERSIONINFO_H

// DEFAULT INFORMATIONS
#define STR_COMPANYNAME "uvnc bvba"
#define STR_COPYRIGHT "Copyright © 2002-2024 UltraVNC Team Members. All Rights Reserved."


// ======================== Define Version here =======================
// MAIN VERSION - ULTRAVNC VIEWER AND ULTRAVNC SERVER
#define 1MAJ 1
#define 1MIN 4
#define 1V3 4
#define 1V4 0 // Used as ReleaseCandidate minor version in SpecialBuildDescription

// VERSION FOR ULTRAVNC ADDONS
#define 2MAJ 1
#define 2MIN 4
#define 2V3 4
#define 2V4 0 // Used as ReleaseCandidate minor version in SpecialBuildDescription

// VERSION FOR ULTRAVNC MSRC4PLUGIN
#define 3MAJ 1
#define 3MIN 4
#define 3V3 4
#define 3V4 0 // Used as ReleaseCandidate minor version in SpecialBuildDescription

// VERSION FOR ULTRAVNC MSRC4PLUGIN_CRYPTO
#define 4MAJ 1
#define 4MIN 4
#define 4V3 4
#define 4V4 0 // Used as ReleaseCandidate minor version in SpecialBuildDescription

// VERSION FOR ULTRAVNC REPEATER
#define 5MAJ 1
#define 5MIN 4
#define 5V3 4
#define 5V4 0 // Used as ReleaseCandidate minor version in SpecialBuildDescription

// VERSION FOR ULTRAVNC SETCAD
#define 6MAJ 1
#define 6MIN 4
#define 6V3 4
#define 6V4 0 // Used as ReleaseCandidate minor version in SpecialBuildDescription

// VERSION FOR ULTRAVNC SETPASSWORD
#define 7MAJ 1
#define 7MIN 4
#define 7V3 4
#define 7V4 0 // Used as ReleaseCandidate minor version in SpecialBuildDescription

// VERSION FOR ULTRAVNC UVNCKEYBOARDHELPER
#define 8MAJ 1
#define 8MIN 4
#define 8V3 4
#define 8V4 0 // Used as ReleaseCandidate minor version in SpecialBuildDescription

// VERSION FOR ULTRAVNC UVNC_SETTINGS
#define 9MAJ 1
#define 9MIN 4
#define 9V3 4
#define 9V4 0 // Used as ReleaseCandidate minor version in SpecialBuildDescription

// VERSION FOR ULTRAVNC CREATEPASSWORD
#define 10MAJ 1
#define 10MIN 4
#define 10V3 4
#define 10V4 0 // Used as ReleaseCandidate minor version in SpecialBuildDescription

// VERSION FOR ULTRAVNC VNCHOOKS
#define 11MAJ 1
#define 11MIN 4
#define 11V3 4
#define 11V4 0 // Used as ReleaseCandidate minor version in SpecialBuildDescription


// Set to 1 if ReleaseCandidate (toggles visibility of SpecialBuildDescription)
#define isRC 0


// =========== No further configuration needed below this line =================

// some helper macros (see http://http://gcc.gnu.org/onlinedocs/cpp/Stringification.html)
#define XSTR(x) STR(x)
#define STR(x) #x


// Concatenate tokens
#define CAT2(A,B) A.B
#define CAT4(A,B,C,D) A.B.C.D


// MAIN VERSION - ULTRAVNC VIEWER AND ULTRAVNC SERVER

#define INT_VERSION_VS 1MAJ,1MIN,1V3,1V4
#define STR_VERSION_VS CAT4(1MAJ,1MIN,1V3,1V4)
#define STR_MAINVER_VS CAT2(1MAJ,1MIN)
#define STR_RC_VERSION_VS CAT2(1V3,1V4)

#define INT_FILEVERSION_VS INT_VERSION_VS
#define INT_PRODUCTVERSION_VS INT_VERSION_VS

#define STR_FILEVERSION_VS XSTR(STR_VERSION_VS)
#define STR_PRODUCTVERSION_VS XSTR(STR_VERSION_VS)

#define STR_SPECIALBUILD_VS "v" XSTR(STR_MAINVER_VS) " ReleaseCandidate " XSTR(STR_RC_VERSION_VS)
#if isRC == 1
#define STR_ABOUT_SERVER_VERSION XSTR(UltraVNC Server v STR_MAINVER_VS RC STR_RC_VERSION_VS)
#define STR_ABOUT_VIEWER_VERSION XSTR(UltraVNC Viewer v STR_MAINVER_VS RC STR_RC_VERSION_VS)
#else
#define STR_ABOUT_SERVER_VERSION XSTR(UltraVNC Server v STR_VERSION_VS)
#define STR_ABOUT_VIEWER_VERSION XSTR(UltraVNC Viewer v STR_VERSION_VS)
#endif

// VERSION FOR ULTRAVNC ADDONS

#define INT_VERSION_ADDON 2MAJ,2MIN,2V3,2V4
#define STR_VERSION_ADDON CAT4(2MAJ,2MIN,2V3,2V4)
#define STR_MAINVER_ADDON CAT2(2MAJ,2MIN)
#define STR_RC_VERSION_ADDON CAT2(2V3,2V4)

#define INT_FILEVERSION_ADDON INT_VERSION_ADDON
#define INT_PRODUCTVERSION_ADDON INT_VERSION_ADDON

#define STR_FILEVERSION_ADDON XSTR(STR_VERSION_ADDON)
#define STR_PRODUCTVERSION_ADDON XSTR(STR_VERSION_ADDON)

#define STR_SPECIALBUILD_ADDON "v" XSTR(STR_MAINVER_ADDON) " ReleaseCandidate " XSTR(STR_RC_VERSION_ADDON)
#if isRC == 1
#define STR_ABOUT_VERSION XSTR( v STR_MAINVER_ADDON RC STR_RC_VERSION_ADDON)
#else
#define STR_ABOUT_VERSION XSTR( v STR_VERSION_ADDON)
#endif


// VERSION FOR ULTRAVNC MSRC4PLUGIN

#define INT_VERSION_MSRC4PLUGIN 3MAJ,3MIN,3V3,3V4
#define STR_VERSION_MSRC4PLUGIN CAT4(3MAJ,3MIN,3V3,3V4)
#define STR_MAINVER_MSRC4PLUGIN CAT2(3MAJ,3MIN)
#define STR_RC_VERSION_MSRC4PLUGIN CAT2(3V3,3V4)

#define INT_FILEVERSION_MSRC4PLUGIN INT_VERSION_MSRC4PLUGIN
#define INT_PRODUCTVERSION_MSRC4PLUGIN INT_VERSION_MSRC4PLUGIN

#define STR_FILEVERSION_MSRC4PLUGIN XSTR(STR_VERSION_MSRC4PLUGIN)
#define STR_PRODUCTVERSION_MSRC4PLUGIN XSTR(STR_VERSION_MSRC4PLUGIN)

#define STR_SPECIALBUILD_MSRC4PLUGIN "v" XSTR(STR_MAINVER_MSRC4PLUGIN) " ReleaseCandidate " XSTR(STR_RC_VERSION_MSRC4PLUGIN)
#if isRC == 1
#define STR_ABOUT_VERSION XSTR( v STR_MAINVER_MSRC4PLUGIN RC STR_RC_VERSION_MSRC4PLUGIN)
#else
#define STR_ABOUT_VERSION XSTR( v STR_VERSION_MSRC4PLUGIN)
#endif


// VERSION FOR ULTRAVNC MSRC4PLUGIN_CRYPTO

#define INT_VERSION_MSRC4PLUGIN_CRYPTO 4MAJ,4MIN,4V3,4V4
#define STR_VERSION_MSRC4PLUGIN_CRYPTO CAT4(4MAJ,4MIN,4V3,4V4)
#define STR_MAINVER_MSRC4PLUGIN_CRYPTO CAT2(4MAJ,4MIN)
#define STR_RC_VERSION_MSRC4PLUGIN_CRYPTO CAT2(4V3,4V4)

#define INT_FILEVERSION_MSRC4PLUGIN_CRYPTO INT_VERSION_MSRC4PLUGIN_CRYPTO
#define INT_PRODUCTVERSION_MSRC4PLUGIN_CRYPTO INT_VERSION_MSRC4PLUGIN_CRYPTO

#define STR_FILEVERSION_MSRC4PLUGIN_CRYPTO XSTR(STR_VERSION_MSRC4PLUGIN_CRYPTO)
#define STR_PRODUCTVERSION_MSRC4PLUGIN_CRYPTO XSTR(STR_VERSION_MSRC4PLUGIN_CRYPTO)

#define STR_SPECIALBUILD_MSRC4PLUGIN_CRYPTO "v" XSTR(STR_MAINVER_MSRC4PLUGIN_CRYPTO) " ReleaseCandidate " XSTR(STR_RC_VERSION_MSRC4PLUGIN_CRYPTO)
#if isRC == 1
#define STR_ABOUT_VERSION XSTR( v STR_MAINVER_MSRC4PLUGIN_CRYPTO RC STR_RC_VERSION_MSRC4PLUGIN_CRYPTO)
#else
#define STR_ABOUT_VERSION XSTR( v STR_VERSION_MSRC4PLUGIN_CRYPTO)
#endif


// VERSION FOR ULTRAVNC REPEATER

#define INT_VERSION_REPEATER 5MAJ,5MIN,5V3,5V4
#define STR_VERSION_REPEATER CAT4(5MAJ,5MIN,5V3,5V4)
#define STR_MAINVER_REPEATER CAT2(5MAJ,5MIN)
#define STR_RC_VERSION_REPEATER CAT2(5V3,5V4)

#define INT_FILEVERSION_REPEATER INT_VERSION_REPEATER
#define INT_PRODUCTVERSION_REPEATER INT_VERSION_REPEATER

#define STR_FILEVERSION_REPEATER XSTR(STR_VERSION_REPEATER)
#define STR_PRODUCTVERSION_REPEATER XSTR(STR_VERSION_REPEATER)

#define STR_SPECIALBUILD_REPEATER "v" XSTR(STR_MAINVER_REPEATER) " ReleaseCandidate " XSTR(STR_RC_VERSION_REPEATER)
#if isRC == 1
#define STR_ABOUT_VERSION XSTR( v STR_MAINVER_REPEATER RC STR_RC_VERSION_REPEATER)
#else
#define STR_ABOUT_VERSION XSTR( v STR_VERSION_REPEATER)
#endif


// VERSION FOR ULTRAVNC SETCAD

#define INT_VERSION_SETCAD 6MAJ,6MIN,6V3,6V4
#define STR_VERSION_SETCAD CAT4(6MAJ,6MIN,6V3,6V4)
#define STR_MAINVER_SETCAD CAT2(6MAJ,6MIN)
#define STR_RC_VERSION_SETCAD CAT2(6V3,6V4)

#define INT_FILEVERSION_SETCAD INT_VERSION_SETCAD
#define INT_PRODUCTVERSION_SETCAD INT_VERSION_SETCAD

#define STR_FILEVERSION_SETCAD XSTR(STR_VERSION_SETCAD)
#define STR_PRODUCTVERSION_SETCAD XSTR(STR_VERSION_SETCAD)

#define STR_SPECIALBUILD_SETCAD "v" XSTR(STR_MAINVER_SETCAD) " ReleaseCandidate " XSTR(STR_RC_VERSION_SETCAD)
#if isRC == 1
#define STR_ABOUT_VERSION XSTR( v STR_MAINVER_SETCAD RC STR_RC_VERSION_SETCAD)
#else
#define STR_ABOUT_VERSION XSTR( v STR_VERSION_SETCAD)
#endif


// VERSION FOR ULTRAVNC SETPASSWORD

#define INT_VERSION_SETPASSWORD 7MAJ,7MIN,7V3,7V4
#define STR_VERSION_SETPASSWORD CAT4(7MAJ,7MIN,7V3,7V4)
#define STR_MAINVER_SETPASSWORD CAT2(7MAJ,7MIN)
#define STR_RC_VERSION_SETPASSWORD CAT2(7V3,7V4)

#define INT_FILEVERSION_SETPASSWORD INT_VERSION_SETPASSWORD
#define INT_PRODUCTVERSION_SETPASSWORD INT_VERSION_SETPASSWORD

#define STR_FILEVERSION_SETPASSWORD XSTR(STR_VERSION_SETPASSWORD)
#define STR_PRODUCTVERSION_SETPASSWORD XSTR(STR_VERSION_SETPASSWORD)

#define STR_SPECIALBUILD_SETPASSWORD "v" XSTR(STR_MAINVER_SETPASSWORD) " ReleaseCandidate " XSTR(STR_RC_VERSION_SETPASSWORD)
#if isRC == 1
#define STR_ABOUT_VERSION XSTR( v STR_MAINVER_SETPASSWORD RC STR_RC_VERSION_SETPASSWORD)
#else
#define STR_ABOUT_VERSION XSTR( v STR_VERSION_SETPASSWORD)
#endif


// VERSION FOR ULTRAVNC UVNCKEYBOARDHELPER

#define INT_VERSION_UVNCKEYBOARDHELPER 8MAJ,8MIN,8V3,8V4
#define STR_VERSION_UVNCKEYBOARDHELPER CAT4(8MAJ,8MIN,8V3,8V4)
#define STR_MAINVER_UVNCKEYBOARDHELPER CAT2(8MAJ,8MIN)
#define STR_RC_VERSION_UVNCKEYBOARDHELPER CAT2(8V3,8V4)

#define INT_FILEVERSION_UVNCKEYBOARDHELPER INT_VERSION_UVNCKEYBOARDHELPER
#define INT_PRODUCTVERSION_UVNCKEYBOARDHELPER INT_VERSION_UVNCKEYBOARDHELPER

#define STR_FILEVERSION_UVNCKEYBOARDHELPER XSTR(STR_VERSION_UVNCKEYBOARDHELPER)
#define STR_PRODUCTVERSION_UVNCKEYBOARDHELPER XSTR(STR_VERSION_UVNCKEYBOARDHELPER)

#define STR_SPECIALBUILD_UVNCKEYBOARDHELPER "v" XSTR(STR_MAINVER_UVNCKEYBOARDHELPER) " ReleaseCandidate " XSTR(STR_RC_VERSION_UVNCKEYBOARDHELPER)
#if isRC == 1
#define STR_ABOUT_VERSION XSTR( v STR_MAINVER_UVNCKEYBOARDHELPER RC STR_RC_VERSION_UVNCKEYBOARDHELPER)
#else
#define STR_ABOUT_VERSION XSTR( v STR_VERSION_UVNCKEYBOARDHELPER)
#endif


// VERSION FOR ULTRAVNC UVNC_SETTINGS

#define INT_VERSION_UVNC_SETTINGS 9MAJ,9MIN,9V3,9V4
#define STR_VERSION_UVNC_SETTINGS CAT4(9MAJ,9MIN,9V3,9V4)
#define STR_MAINVER_UVNC_SETTINGS CAT2(9MAJ,9MIN)
#define STR_RC_VERSION_UVNC_SETTINGS CAT2(9V3,9V4)

#define INT_FILEVERSION_UVNC_SETTINGS INT_VERSION_UVNC_SETTINGS
#define INT_PRODUCTVERSION_UVNC_SETTINGS INT_VERSION_UVNC_SETTINGS

#define STR_FILEVERSION_UVNC_SETTINGS XSTR(STR_VERSION_UVNC_SETTINGS)
#define STR_PRODUCTVERSION_UVNC_SETTINGS XSTR(STR_VERSION_UVNC_SETTINGS)

#define STR_SPECIALBUILD_UVNC_SETTINGS "v" XSTR(STR_MAINVER_UVNC_SETTINGS) " ReleaseCandidate " XSTR(STR_RC_VERSION_UVNC_SETTINGS)
#if isRC == 1
#define STR_ABOUT_VERSION XSTR( v STR_MAINVER_UVNC_SETTINGS RC STR_RC_VERSION_UVNC_SETTINGS)
#else
#define STR_ABOUT_VERSION XSTR( v STR_VERSION_UVNC_SETTINGS)
#endif


// VERSION FOR ULTRAVNC CREATEPASSWORD

#define INT_VERSION_CREATEPASSWORD 10MAJ,10MIN,10V3,10V4
#define STR_VERSION_CREATEPASSWORD CAT4(10MAJ,10MIN,10V3,10V4)
#define STR_MAINVER_CREATEPASSWORD CAT2(10MAJ,10MIN)
#define STR_RC_VERSION_CREATEPASSWORD CAT2(10V3,10V4)

#define INT_FILEVERSION_CREATEPASSWORD INT_VERSION_CREATEPASSWORD
#define INT_PRODUCTVERSION_CREATEPASSWORD INT_VERSION_CREATEPASSWORD

#define STR_FILEVERSION_CREATEPASSWORD XSTR(STR_VERSION_CREATEPASSWORD)
#define STR_PRODUCTVERSION_CREATEPASSWORD XSTR(STR_VERSION_CREATEPASSWORD)

#define STR_SPECIALBUILD_CREATEPASSWORD "v" XSTR(STR_MAINVER_CREATEPASSWORD) " ReleaseCandidate " XSTR(STR_RC_VERSION_CREATEPASSWORD)
#if isRC == 1
#define STR_ABOUT_VERSION XSTR( v STR_MAINVER_CREATEPASSWORD RC STR_RC_VERSION_CREATEPASSWORD)
#else
#define STR_ABOUT_VERSION XSTR( v STR_VERSION_CREATEPASSWORD)
#endif


// VERSION FOR ULTRAVNC VNCHOOKS

#define INT_VERSION_VNCHOOKS 11MAJ,11MIN,11V3,11V4
#define STR_VERSION_VNCHOOKS CAT4(11MAJ,11MIN,11V3,11V4)
#define STR_MAINVER_VNCHOOKS CAT2(11MAJ,11MIN)
#define STR_RC_VERSION_VNCHOOKS CAT2(11V3,11V4)

#define INT_FILEVERSION_VNCHOOKS INT_VERSION_VNCHOOKS
#define INT_PRODUCTVERSION_VNCHOOKS INT_VERSION_VNCHOOKS

#define STR_FILEVERSION_VNCHOOKS XSTR(STR_VERSION_VNCHOOKS)
#define STR_PRODUCTVERSION_VNCHOOKS XSTR(STR_VERSION_VNCHOOKS)

#define STR_SPECIALBUILD_VNCHOOKS "v" XSTR(STR_MAINVER_VNCHOOKS) " ReleaseCandidate " XSTR(STR_RC_VERSION_VNCHOOKS)
#if isRC == 1
#define STR_ABOUT_VERSION XSTR( v STR_MAINVER_VNCHOOKS RC STR_RC_VERSION_VNCHOOKS)
#else
#define STR_ABOUT_VERSION XSTR( v STR_VERSION_VNCHOOKS)
#endif


#endif // ULTRAVNC_VERSIONINFO_H
