/////////////////////////////////////////////////////////////////////////////
//  Copyright (C) 2002-2024 UltraVNC Team Members. All Rights Reserved.
//  Copyright (C) 2004 Martin Scharpf, B. Braun Melsungen AG. All Rights Reserved.
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation; either version 2 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
//  USA.
//
//  If the source code for the program is not available from the place from
//  which you received this file, check
//  https://uvnc.com/
//
////////////////////////////////////////////////////////////////////////////


/* versioninfo.h: Defines 
	STR_COMPANYNAME, 
    STR_FILEVERSION,
	STR_PRODUCTVERSION,
	STR_COPYRIGHT,
	STR_SPECIALBUILD,
	INT_FILEVERSION,
	INT_PRODUCTVERSION */

#ifndef ULTRAVNC_VERSIONINFO_H
#define ULTRAVNC_VERSIONINFO_H

// DEFAULT INFORMATIONS
#define STR_COMPANYNAME "uvnc bvba"
#define STR_COPYRIGHT "Copyright © 2002-2024 UltraVNC Team Members. All Rights Reserved."


// ======================== Define Version here =======================
// MAIN VERSION - ULTRAVNC VIEWER AND ULTRAVNC SERVER
#define MAJ_VS 1
#define MIN_VS 4
#define V3_VS 4
#define V4_VS 0 // Used as ReleaseCandidate minor version in SpecialBuildDescription

// VERSION FOR ULTRAVNC ADDONS
#define MAJ_ADDON 1
#define MIN_ADDON 4
#define V3_ADDON 4
#define V4_ADDON 0 // Used as ReleaseCandidate minor version in SpecialBuildDescription

// VERSION FOR ULTRAVNC MSRC4PLUGIN
#define MAJ_MSRC4PLUGIN 1
#define MIN_MSRC4PLUGIN 4
#define V3_MSRC4PLUGIN 4
#define V4_MSRC4PLUGIN 0 // Used as ReleaseCandidate minor version in SpecialBuildDescription

// VERSION FOR ULTRAVNC MSRC4PLUGIN_CRYPTO
#define MAJ_MSRC4PLUGIN_CRYPTO 1
#define MIN_MSRC4PLUGIN_CRYPTO 4
#define V3_MSRC4PLUGIN_CRYPTO 4
#define V4_MSRC4PLUGIN_CRYPTO 0 // Used as ReleaseCandidate minor version in SpecialBuildDescription

// VERSION FOR ULTRAVNC REPEATER
#define MAJ_REPEATER 1
#define MIN_REPEATER 4
#define V3_REPEATER 4
#define V4_REPEATER 0 // Used as ReleaseCandidate minor version in SpecialBuildDescription

// VERSION FOR ULTRAVNC SETCAD
#define MAJ_SETCAD 1
#define MIN_SETCAD 4
#define V3_SETCAD 4
#define V4_SETCAD 0 // Used as ReleaseCandidate minor version in SpecialBuildDescription

// VERSION FOR ULTRAVNC SETPASSWORD
#define MAJ_SETPASSWORD 1
#define MIN_SETPASSWORD 4
#define V3_SETPASSWORD 4
#define V4_SETPASSWORD 0 // Used as ReleaseCandidate minor version in SpecialBuildDescription

// VERSION FOR ULTRAVNC UVNCKEYBOARDHELPER
#define MAJ_UVNCKEYBOARDHELPER 1
#define MIN_UVNCKEYBOARDHELPER 4
#define V3_UVNCKEYBOARDHELPER 4
#define V4_UVNCKEYBOARDHELPER 0 // Used as ReleaseCandidate minor version in SpecialBuildDescription

// VERSION FOR ULTRAVNC UVNC_SETTINGS
#define MAJ_UVNC_SETTINGS 1
#define MIN_UVNC_SETTINGS 4
#define V3_UVNC_SETTINGS 4
#define V4_UVNC_SETTINGS 0 // Used as ReleaseCandidate minor version in SpecialBuildDescription

// VERSION FOR ULTRAVNC CREATEPASSWORD
#define MAJ_CREATEPASSWORD 1
#define MIN_CREATEPASSWORD 4
#define V3_CREATEPASSWORD 4
#define V4_CREATEPASSWORD 0 // Used as ReleaseCandidate minor version in SpecialBuildDescription

// VERSION FOR ULTRAVNC VNCHOOKS
#define MAJ_VNCHOOKS 1
#define MIN_VNCHOOKS 4
#define V3_VNCHOOKS 4
#define V4_VNCHOOKS 0 // Used as ReleaseCandidate minor version in SpecialBuildDescription


// Set to 1 if ReleaseCandidate (toggles visibility of SpecialBuildDescription)
#define isRC 0


// =========== No further configuration needed below this line =================

// some helper macros (see http://http://gcc.gnu.org/onlinedocs/cpp/Stringification.html)
#define XSTR(x) STR(x)
#define STR(x) #x


// Concatenate tokens
#define CAT2(A,B) A.B
#define CAT4(A,B,C,D) A.B.C.D


// MAIN VERSION - ULTRAVNC VIEWER AND ULTRAVNC SERVER

#define INT_VERSION_VS MAJ_VS,MIN_VS,V3_VS,V4_VS
#define STR_VERSION_VS CAT4(MAJ_VS,MIN_VS,V3_VS,V4_VS)
#define STR_MAINVER_VS CAT2(MAJ_VS,MIN_VS)
#define STR_RC_VERSION_VS CAT2(V3_VS,V4_VS)

#define INT_FILEVERSION_VS INT_VERSION_VS
#define INT_PRODUCTVERSION_VS INT_VERSION_VS

#define STR_FILEVERSION_VS XSTR(STR_VERSION_VS)
#define STR_PRODUCTVERSION_VS XSTR(STR_VERSION_VS)

#define STR_SPECIALBUILD_VS "v" XSTR(STR_MAINVER_VS) " ReleaseCandidate " XSTR(STR_RC_VERSION_VS)
#if isRC == 1
#define STR_ABOUT_SERVER_VERSION XSTR(UltraVNC Server v STR_MAINVER_VS RC STR_RC_VERSION_VS)
#define STR_ABOUT_VIEWER_VERSION XSTR(UltraVNC Viewer v STR_MAINVER_VS RC STR_RC_VERSION_VS)
#else
#define STR_ABOUT_SERVER_VERSION XSTR(UltraVNC Server v STR_VERSION_VS)
#define STR_ABOUT_VIEWER_VERSION XSTR(UltraVNC Viewer v STR_VERSION_VS)
#endif

// VERSION FOR ULTRAVNC ADDONS

#define INT_VERSION_ADDON MAJ_ADDON,MIN_ADDON,V3_ADDON,V4_ADDON
#define STR_VERSION_ADDON CAT4(MAJ_ADDON,MIN_ADDON,V3_ADDON,V4_ADDON)
#define STR_MAINVER_ADDON CAT2(MAJ_ADDON,MIN_ADDON)
#define STR_RC_VERSION_ADDON CAT2(V3_ADDON,V4_ADDON)

#define INT_FILEVERSION_ADDON INT_VERSION_ADDON
#define INT_PRODUCTVERSION_ADDON INT_VERSION_ADDON

#define STR_FILEVERSION_ADDON XSTR(STR_VERSION_ADDON)
#define STR_PRODUCTVERSION_ADDON XSTR(STR_VERSION_ADDON)

#define STR_SPECIALBUILD_ADDON "v" XSTR(STR_MAINVER_ADDON) " ReleaseCandidate " XSTR(STR_RC_VERSION_ADDON)
#if isRC == 1
#define STR_ABOUT_VERSION_ADDON XSTR( v STR_MAINVER_ADDON RC STR_RC_VERSION_ADDON)
#else
#define STR_ABOUT_VERSION_ADDON XSTR( v STR_VERSION_ADDON)
#endif


// VERSION FOR ULTRAVNC MSRC4PLUGIN

#define INT_VERSION_MSRC4PLUGIN MAJ_MSRC4PLUGIN,MIN_MSRC4PLUGIN,V3_MSRC4PLUGIN,V4_MSRC4PLUGIN
#define STR_VERSION_MSRC4PLUGIN CAT4(MAJ_MSRC4PLUGIN,MIN_MSRC4PLUGIN,V3_MSRC4PLUGIN,V4_MSRC4PLUGIN)
#define STR_MAINVER_MSRC4PLUGIN CAT2(MAJ_MSRC4PLUGIN,MIN_MSRC4PLUGIN)
#define STR_RC_VERSION_MSRC4PLUGIN CAT2(V3_MSRC4PLUGIN,V4_MSRC4PLUGIN)

#define INT_FILEVERSION_MSRC4PLUGIN INT_VERSION_MSRC4PLUGIN
#define INT_PRODUCTVERSION_MSRC4PLUGIN INT_VERSION_MSRC4PLUGIN

#define STR_FILEVERSION_MSRC4PLUGIN XSTR(STR_VERSION_MSRC4PLUGIN)
#define STR_PRODUCTVERSION_MSRC4PLUGIN XSTR(STR_VERSION_MSRC4PLUGIN)

#define STR_SPECIALBUILD_MSRC4PLUGIN "v" XSTR(STR_MAINVER_MSRC4PLUGIN) " ReleaseCandidate " XSTR(STR_RC_VERSION_MSRC4PLUGIN)
#if isRC == 1
#define STR_ABOUT_VERSION_MSRC4PLUGIN XSTR( v STR_MAINVER_MSRC4PLUGIN RC STR_RC_VERSION_MSRC4PLUGIN)
#else
#define STR_ABOUT_VERSION_MSRC4PLUGIN XSTR( v STR_VERSION_MSRC4PLUGIN)
#endif


// VERSION FOR ULTRAVNC MSRC4PLUGIN_CRYPTO

#define INT_VERSION_MSRC4PLUGIN_CRYPTO MAJ_MSRC4PLUGIN_CRYPTO,MIN_MSRC4PLUGIN_CRYPTO,V3_MSRC4PLUGIN_CRYPTO,V4_MSRC4PLUGIN_CRYPTO
#define STR_VERSION_MSRC4PLUGIN_CRYPTO CAT4(MAJ_MSRC4PLUGIN_CRYPTO,MIN_MSRC4PLUGIN_CRYPTO,V3_MSRC4PLUGIN_CRYPTO,V4_MSRC4PLUGIN_CRYPTO)
#define STR_MAINVER_MSRC4PLUGIN_CRYPTO CAT2(MAJ_MSRC4PLUGIN_CRYPTO,MIN_MSRC4PLUGIN_CRYPTO)
#define STR_RC_VERSION_MSRC4PLUGIN_CRYPTO CAT2(V3_MSRC4PLUGIN_CRYPTO,V4_MSRC4PLUGIN_CRYPTO)

#define INT_FILEVERSION_MSRC4PLUGIN_CRYPTO INT_VERSION_MSRC4PLUGIN_CRYPTO
#define INT_PRODUCTVERSION_MSRC4PLUGIN_CRYPTO INT_VERSION_MSRC4PLUGIN_CRYPTO

#define STR_FILEVERSION_MSRC4PLUGIN_CRYPTO XSTR(STR_VERSION_MSRC4PLUGIN_CRYPTO)
#define STR_PRODUCTVERSION_MSRC4PLUGIN_CRYPTO XSTR(STR_VERSION_MSRC4PLUGIN_CRYPTO)

#define STR_SPECIALBUILD_MSRC4PLUGIN_CRYPTO "v" XSTR(STR_MAINVER_MSRC4PLUGIN_CRYPTO) " ReleaseCandidate " XSTR(STR_RC_VERSION_MSRC4PLUGIN_CRYPTO)
#if isRC == 1
#define STR_ABOUT_VERSION_MSRC4PLUGIN_CRYPTO XSTR( v STR_MAINVER_MSRC4PLUGIN_CRYPTO RC STR_RC_VERSION_MSRC4PLUGIN_CRYPTO)
#else
#define STR_ABOUT_VERSION_MSRC4PLUGIN_CRYPTO XSTR( v STR_VERSION_MSRC4PLUGIN_CRYPTO)
#endif


// VERSION FOR ULTRAVNC REPEATER

#define INT_VERSION_REPEATER MAJ_REPEATER,MIN_REPEATER,V3_REPEATER,V4_REPEATER
#define STR_VERSION_REPEATER CAT4(MAJ_REPEATER,MIN_REPEATER,V3_REPEATER,V4_REPEATER)
#define STR_MAINVER_REPEATER CAT2(MAJ_REPEATER,MIN_REPEATER)
#define STR_RC_VERSION_REPEATER CAT2(V3_REPEATER,V4_REPEATER)

#define INT_FILEVERSION_REPEATER INT_VERSION_REPEATER
#define INT_PRODUCTVERSION_REPEATER INT_VERSION_REPEATER

#define STR_FILEVERSION_REPEATER XSTR(STR_VERSION_REPEATER)
#define STR_PRODUCTVERSION_REPEATER XSTR(STR_VERSION_REPEATER)

#define STR_SPECIALBUILD_REPEATER "v" XSTR(STR_MAINVER_REPEATER) " ReleaseCandidate " XSTR(STR_RC_VERSION_REPEATER)
#if isRC == 1
#define STR_ABOUT_VERSION_REPEATER XSTR( v STR_MAINVER_REPEATER RC STR_RC_VERSION_REPEATER)
#else
#define STR_ABOUT_VERSION_REPEATER XSTR( v STR_VERSION_REPEATER)
#endif


// VERSION FOR ULTRAVNC SETCAD

#define INT_VERSION_SETCAD MAJ_SETCAD,MIN_SETCAD,V3_SETCAD,V4_SETCAD
#define STR_VERSION_SETCAD CAT4(MAJ_SETCAD,MIN_SETCAD,V3_SETCAD,V4_SETCAD)
#define STR_MAINVER_SETCAD CAT2(MAJ_SETCAD,MIN_SETCAD)
#define STR_RC_VERSION_SETCAD CAT2(V3_SETCAD,V4_SETCAD)

#define INT_FILEVERSION_SETCAD INT_VERSION_SETCAD
#define INT_PRODUCTVERSION_SETCAD INT_VERSION_SETCAD

#define STR_FILEVERSION_SETCAD XSTR(STR_VERSION_SETCAD)
#define STR_PRODUCTVERSION_SETCAD XSTR(STR_VERSION_SETCAD)

#define STR_SPECIALBUILD_SETCAD "v" XSTR(STR_MAINVER_SETCAD) " ReleaseCandidate " XSTR(STR_RC_VERSION_SETCAD)
#if isRC == 1
#define STR_ABOUT_VERSION_SETCAD XSTR( v STR_MAINVER_SETCAD RC STR_RC_VERSION_SETCAD)
#else
#define STR_ABOUT_VERSION_SETCAD XSTR( v STR_VERSION_SETCAD)
#endif


// VERSION FOR ULTRAVNC SETPASSWORD

#define INT_VERSION_SETPASSWORD MAJ_SETPASSWORD,MIN_SETPASSWORD,V3_SETPASSWORD,V4_SETPASSWORD
#define STR_VERSION_SETPASSWORD CAT4(MAJ_SETPASSWORD,MIN_SETPASSWORD,V3_SETPASSWORD,V4_SETPASSWORD)
#define STR_MAINVER_SETPASSWORD CAT2(MAJ_SETPASSWORD,MIN_SETPASSWORD)
#define STR_RC_VERSION_SETPASSWORD CAT2(V3_SETPASSWORD,V4_SETPASSWORD)

#define INT_FILEVERSION_SETPASSWORD INT_VERSION_SETPASSWORD
#define INT_PRODUCTVERSION_SETPASSWORD INT_VERSION_SETPASSWORD

#define STR_FILEVERSION_SETPASSWORD XSTR(STR_VERSION_SETPASSWORD)
#define STR_PRODUCTVERSION_SETPASSWORD XSTR(STR_VERSION_SETPASSWORD)

#define STR_SPECIALBUILD_SETPASSWORD "v" XSTR(STR_MAINVER_SETPASSWORD) " ReleaseCandidate " XSTR(STR_RC_VERSION_SETPASSWORD)
#if isRC == 1
#define STR_ABOUT_VERSION_SETPASSWORD XSTR( v STR_MAINVER_SETPASSWORD RC STR_RC_VERSION_SETPASSWORD)
#else
#define STR_ABOUT_VERSION_SETPASSWORD XSTR( v STR_VERSION_SETPASSWORD)
#endif


// VERSION FOR ULTRAVNC UVNCKEYBOARDHELPER

#define INT_VERSION_UVNCKEYBOARDHELPER MAJ_UVNCKEYBOARDHELPER,MIN_UVNCKEYBOARDHELPER,V3_UVNCKEYBOARDHELPER,V4_UVNCKEYBOARDHELPER
#define STR_VERSION_UVNCKEYBOARDHELPER CAT4(MAJ_UVNCKEYBOARDHELPER,MIN_UVNCKEYBOARDHELPER,V3_UVNCKEYBOARDHELPER,V4_UVNCKEYBOARDHELPER)
#define STR_MAINVER_UVNCKEYBOARDHELPER CAT2(MAJ_UVNCKEYBOARDHELPER,MIN_UVNCKEYBOARDHELPER)
#define STR_RC_VERSION_UVNCKEYBOARDHELPER CAT2(V3_UVNCKEYBOARDHELPER,V4_UVNCKEYBOARDHELPER)

#define INT_FILEVERSION_UVNCKEYBOARDHELPER INT_VERSION_UVNCKEYBOARDHELPER
#define INT_PRODUCTVERSION_UVNCKEYBOARDHELPER INT_VERSION_UVNCKEYBOARDHELPER

#define STR_FILEVERSION_UVNCKEYBOARDHELPER XSTR(STR_VERSION_UVNCKEYBOARDHELPER)
#define STR_PRODUCTVERSION_UVNCKEYBOARDHELPER XSTR(STR_VERSION_UVNCKEYBOARDHELPER)

#define STR_SPECIALBUILD_UVNCKEYBOARDHELPER "v" XSTR(STR_MAINVER_UVNCKEYBOARDHELPER) " ReleaseCandidate " XSTR(STR_RC_VERSION_UVNCKEYBOARDHELPER)
#if isRC == 1
#define STR_ABOUT_VERSION_UVNCKEYBOARDHELPER XSTR( v STR_MAINVER_UVNCKEYBOARDHELPER RC STR_RC_VERSION_UVNCKEYBOARDHELPER)
#else
#define STR_ABOUT_VERSION_UVNCKEYBOARDHELPER XSTR( v STR_VERSION_UVNCKEYBOARDHELPER)
#endif


// VERSION FOR ULTRAVNC UVNC_SETTINGS

#define INT_VERSION_UVNC_SETTINGS MAJ_UVNC_SETTINGS,MIN_UVNC_SETTINGS,V3_UVNC_SETTINGS,V4_UVNC_SETTINGS
#define STR_VERSION_UVNC_SETTINGS CAT4(MAJ_UVNC_SETTINGS,MIN_UVNC_SETTINGS,V3_UVNC_SETTINGS,V4_UVNC_SETTINGS)
#define STR_MAINVER_UVNC_SETTINGS CAT2(MAJ_UVNC_SETTINGS,MIN_UVNC_SETTINGS)
#define STR_RC_VERSION_UVNC_SETTINGS CAT2(V3_UVNC_SETTINGS,V4_UVNC_SETTINGS)

#define INT_FILEVERSION_UVNC_SETTINGS INT_VERSION_UVNC_SETTINGS
#define INT_PRODUCTVERSION_UVNC_SETTINGS INT_VERSION_UVNC_SETTINGS

#define STR_FILEVERSION_UVNC_SETTINGS XSTR(STR_VERSION_UVNC_SETTINGS)
#define STR_PRODUCTVERSION_UVNC_SETTINGS XSTR(STR_VERSION_UVNC_SETTINGS)

#define STR_SPECIALBUILD_UVNC_SETTINGS "v" XSTR(STR_MAINVER_UVNC_SETTINGS) " ReleaseCandidate " XSTR(STR_RC_VERSION_UVNC_SETTINGS)
#if isRC == 1
#define STR_ABOUT_VERSION_UVNC_SETTINGS XSTR( v STR_MAINVER_UVNC_SETTINGS RC STR_RC_VERSION_UVNC_SETTINGS)
#else
#define STR_ABOUT_VERSION_UVNC_SETTINGS XSTR( v STR_VERSION_UVNC_SETTINGS)
#endif


// VERSION FOR ULTRAVNC CREATEPASSWORD

#define INT_VERSION_CREATEPASSWORD MAJ_CREATEPASSWORD,MIN_CREATEPASSWORD,V3_CREATEPASSWORD,V4_CREATEPASSWORD
#define STR_VERSION_CREATEPASSWORD CAT4(MAJ_CREATEPASSWORD,MIN_CREATEPASSWORD,V3_CREATEPASSWORD,V4_CREATEPASSWORD)
#define STR_MAINVER_CREATEPASSWORD CAT2(MAJ_CREATEPASSWORD,MIN_CREATEPASSWORD)
#define STR_RC_VERSION_CREATEPASSWORD CAT2(V3_CREATEPASSWORD,V4_CREATEPASSWORD)

#define INT_FILEVERSION_CREATEPASSWORD INT_VERSION_CREATEPASSWORD
#define INT_PRODUCTVERSION_CREATEPASSWORD INT_VERSION_CREATEPASSWORD

#define STR_FILEVERSION_CREATEPASSWORD XSTR(STR_VERSION_CREATEPASSWORD)
#define STR_PRODUCTVERSION_CREATEPASSWORD XSTR(STR_VERSION_CREATEPASSWORD)

#define STR_SPECIALBUILD_CREATEPASSWORD "v" XSTR(STR_MAINVER_CREATEPASSWORD) " ReleaseCandidate " XSTR(STR_RC_VERSION_CREATEPASSWORD)
#if isRC == 1
#define STR_ABOUT_VERSION_CREATEPASSWORD XSTR( v STR_MAINVER_CREATEPASSWORD RC STR_RC_VERSION_CREATEPASSWORD)
#else
#define STR_ABOUT_VERSION_CREATEPASSWORD XSTR( v STR_VERSION_CREATEPASSWORD)
#endif


// VERSION FOR ULTRAVNC VNCHOOKS

#define INT_VERSION_VNCHOOKS MAJ_VNCHOOKS,MIN_VNCHOOKS,V3_VNCHOOKS,V4_VNCHOOKS
#define STR_VERSION_VNCHOOKS CAT4(MAJ_VNCHOOKS,MIN_VNCHOOKS,V3_VNCHOOKS,V4_VNCHOOKS)
#define STR_MAINVER_VNCHOOKS CAT2(MAJ_VNCHOOKS,MIN_VNCHOOKS)
#define STR_RC_VERSION_VNCHOOKS CAT2(V3_VNCHOOKS,V4_VNCHOOKS)

#define INT_FILEVERSION_VNCHOOKS INT_VERSION_VNCHOOKS
#define INT_PRODUCTVERSION_VNCHOOKS INT_VERSION_VNCHOOKS

#define STR_FILEVERSION_VNCHOOKS XSTR(STR_VERSION_VNCHOOKS)
#define STR_PRODUCTVERSION_VNCHOOKS XSTR(STR_VERSION_VNCHOOKS)

#define STR_SPECIALBUILD_VNCHOOKS "v" XSTR(STR_MAINVER_VNCHOOKS) " ReleaseCandidate " XSTR(STR_RC_VERSION_VNCHOOKS)
#if isRC == 1
#define STR_ABOUT_VERSION_VNCHOOKS XSTR( v STR_MAINVER_VNCHOOKS RC STR_RC_VERSION_VNCHOOKS)
#else
#define STR_ABOUT_VERSION_VNCHOOKS XSTR( v STR_VERSION_VNCHOOKS)
#endif


#endif // ULTRAVNC_VERSIONINFO_H
