// This file is part of UltraVNC
// https://github.com/ultravnc/UltraVNC
// https://uvnc.com/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// SPDX-FileCopyrightText: Copyright (C) 2002-2025 UltraVNC Team Members. All Rights Reserved.
// SPDX-FileCopyrightText: Copyright (C) 1999-2002 Vdacc-VNC & eSVNC Projects. All Rights Reserved.
//


#define APS_MAJORNUMBER          1
#define APS_MINORNUMBER          7
#define APS_BUILDNUMBER          0
#define APS_MODIFICATIONNUMBER   0
#define APS_DATEYEAR          2025
