//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by uvnc_settings.rc
//
#define IDC_MYICON                      2
#define IDD_UVNC_SETTINGS_DIALOG        102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDD_PASSWD                      104
#define IDM_ABOUT                       105
#define IDM_EXIT                        106
#define IDC_UVNC_SETTINGS               109
#define IDR_MAINFRAME                   128
#define IDD_OPTION1                     129
#define IDD_INCOMING                    129
#define IDD_MSLOGON                     131
#define IDI_ICON1                       133
#define IDD_OPTION8                     1001
#define IDD_SERVICE                     1001
#define IDD_OPTION9                     1002
#define IDC_TESTNET                     1003
#define IDC_UPNPON                      1004
#define IDC_TAB                         1005
#define IDC_UPNPOFF                     1006
#define IDC_LOCAL                       1007
#define IDC_REMOTE                      1008
#define IDC_EDIT3                       1009
#define IDC_PASSWORD                    1010
#define IDC_MSLOGON_CHECKD              1011
#define IDC_NEW_MSLOGON                 1012
#define IDC_MSLOGON                     1013
#define IDC_PLUGIN_CHECK                1014
#define IDC_PLUGINS_COMBO               1015
#define IDC_PLUGIN_BUTTON               1016
#define IDC_FILETRANSFER                1017
#define IDC_PASSWORD2                   1017
#define IDC_FTUSERIMPERSONATION_CHECK   1018
#define IDC_LOCKSETTING_NOTHING         1019
#define IDC_LOCKSETTING_LOCK            1020
#define IDC_LOCKSETTING_LOGOFF          1021
#define IDQUERY                         1022
#define IDC_RADIO4                      1023
#define IDC_MV1                         1024
#define IDC_RADIO5                      1025
#define IDC_MV2                         1026
#define IDC_RADIO6                      1027
#define IDC_MV3                         1028
#define IDC_RADIO7                      1029
#define IDC_MV4                         1030
#define IDQUERYTIMEOUT                  1031
#define IDC_DREFUSE                     1032
#define IDC_DACCEPT                     1033
#define IDC_DRefuseOnly                 1034
#define IDC_LOG                         1035
#define IDC_VIDEO                       1036
#define IDC_EDIT_PATH                   1037
#define IDC_CLEAR                       1038
#define IDC_POLL_FULLSCREEN             1039
#define IDC_POLL_FOREGROUND             1040
#define IDC_CONSOLE_ONLY                1041
#define IDC_POLL_UNDER_CURSOR           1042
#define IDC_ONEVENT_ONLY                1043
#define IDC_TURBOMODE                   1044
#define IDC_HOOK                        1045
#define IDC_DRIVER                      1046
#define IDC_REMOVE_Aero                 1048
#define IDC_REMOVE_WALLPAPER            1049
#define IDC_CHECKDRIVER                 1050
#define IDC_DISABLE_INPUTS              1051
#define IDC_DISABLE_LOCAL_INPUTS        1052
#define IDC_JAP_INPUTS                  1053
#define IDC_CHECK4                      1054
#define IDC_BLANK                       1055
#define IDC_CHECKREP                    1056
#define IDC_BLANK2                      1057
#define IDC_POWER                       1058
#define IDC_DISABLETRAY                 1059
#define IDC_ALLOWSHUTDOWN               1060
#define IDC_SCALE                       1061
#define IDC_FTTIMEOUT                   1062
#define IDC_IDLE                        1063
#define IDC_AUTHHOST                    1064
#define IDC_QNOLOGON                    1065
#define IDC_FILE                        1066
#define IDC_WINDOW                      1068
#define IDC_ALL                         1069
#define IDC_INFO                        1070
#define IDC_WARN                        1071
#define IDC_CHECK1                      1072
#define IDC_MAXCPU                      1072
#define IDC_RDPMODE                     1072
#define IDC_DISINI                      1073
#define IDC_CHECKUSEENCRYPTION          1074
#define IDC_ALLOWEDIT                   1075
#define IDC_ALLOWPROP                   1076
#define IDC_CHECKUPNP                   1077
#define IDC_FIXUPNP                     1078
#define IDC_PASSRECK                    1079
#define IDC_IDLETIME                    1080
#define IDC_KICKRDP                     1081
#define IDC_EDIT1                       1082
#define IDC_SFXPASSWD                   1082
#define IDC_QMESG                       1082
#define IDC_MAXFPS                      1082
#define IDC_SCL                         1083
#define IDC_EDITOUTSERV                 1084
#define IDC_EDITNAME                    1085
#define IDC_CHECKUSESERVICE             1086
#define IDC_RADIOLAN                    1087
#define IDC_RADIOINTERNET               1088
#define IDC_INVERSPORT                  1089
#define IDC_GROUP1                      1090
#define IDC_GROUP2                      1091
#define IDC_CREATESFX                   1092
#define IDC_GROUP3                      1093
#define IDC_CHECKRECON                  1094
#define IDC_CHECKG1L                    1095
#define IDC_EDITID                      1096
#define IDC_CHECKG2L                    1097
#define IDC_EDITOUTVIEW                 1098
#define IDC_CHECKG3L                    1099
#define IDC_CHECKG1D                    1100
#define IDC_CHECKG2D                    1101
#define IDC_CHECKG3D                    1102
#define IDC_EDITREP                     1103
#define IDC_NEXT                        1104
#define IDC_BACK                        1105
#define IDC_MANUAL                      1106
#define IDC_EDIT2                       1107
#define IDC_SOCKETTIMEOUT               1107
#define IDC_IDLETIMEINPUT               1107
#define IDC_LOCALIP                     1108
#define IDC_REMOTEIP                    1109
#define IDC_EDITVPORT                   1110
#define IDC_EDITSPORT                   1111
#define IDC_PRIM                        1111
#define IDC_SEC                         1112
#define IDC_RADIO1                      1113
#define IDC_KINTERVAL                   1114
#define IDC_INSTALSS                    1115
#define IDC_UNINSTALLS                  1116
#define IDC_STARTS                      1117
#define IDC_STOPS                       1118
#define IDC_HELP2                       1120
#define IDD_PARENT                      1200
#define IDC_CONNECT_SOCK                1201
#define IDD_OPTION2                     1202
#define IDD_SECURITY                    1202
#define IDC_CONNECT_HTTP                1203
#define IDC_PORTRFB                     1204
#define IDD_OPTION3                     1205
#define IDD_FILETRANSFER                1205
#define IDC_PORTHTTP                    1206
#define IDD_OPTION4                     1207
#define IDD_CONNECTION                  1207
#define IDC_PORTNO_AUTO                 1208
#define IDD_OPTION5                     1209
#define IDD_CAPTURE                     1209
#define IDC_SPECPORT                    1210
#define IDC_ALLOWLOOPBACK               1211
#define IDD_OPTION7                     1212
#define IDD_MISC                        1212
#define IDC_LOOPBACKONLY                1213
#define IDD_PASSWDBOX                   1213
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1121
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
