//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by winvnc.rc
//
#define IDI_WINVNC                      9
#define IDACCEPT                        10
#define IDQUERY                         11
#define IDQUERYTIMEOUT                  12
#define IDREJECT                        13
#define IDR_BLOCKCIPHER_CLASS           101
#define IDR_CIPHER_CLASS                102
#define IDR_CRYPTOUTILS_CLASS           103
#define IDR_IDEACIPHER_CLASS            104
#define IDR_JAVAARCHIVE1                105
#define IDR_MESSAGES_CLASS              106
#define IDR_MESSAGES_PROPERTIES         107
#define IDR_TRAYMENU                    108
#define IDR_TRAYMENU1                   109
#define IDR_VNCVIEWER_JAR               110
#define IDB_BITMAP1                     111
#define IDB_BITMAP2                     112
#define IDB_BITMAP3                     113
#define IDB_BITMAP4                     114
#define IDB_COLLAPS                     115
#define IDB_EXPAND                      116
#define IDB_GREEN                       117
#define IDB_LOGO64                      118
#define IDB_RED                         119
#define IDB_VNCLOGO                     120
#define IDB_YELLOW                      121
#define IDI_FLASH                       122
#define IDD_ABOUT                       124
#define IDD_ACCEPT_CONN                 125
#define IDD_AUTH_DIALOG                 126
#define IDD_DIALOGCLOUD                 127
#define IDD_DOMAIN                      128
#define IDD_LIST_DLG                    129
#define IDD_LOGON                       130
#define IDD_MSLOGON                     131
#define IDD_OUTGOING_CONN               132
#define IDD_PASSWORD                    133
#define IDD_PATHS                       134
#define IDD_PROPERTIES                  135
#define IDD_PROPERTIES1                 136
#define IDD_TEXTCHAT_DLG                137
#define IDD_USER_NAME                   138
#if defined(SC_20)
	#define IDR_DLL1                    176
	#define IDR_ENCRYPTIONDLL1          177
#endif // SC_20
#define IDS_WARNING                     200
#define IDC_ACCEPTLOGO                  1001
#define IDC_ACCEPT_IP                   1002
#define IDC_ACCEPT_TIMEOUT              1003
#define IDC_ALLOWEDITCLIENTS            1004
#define IDC_ALLOWLOOPBACK               1005
#define IDC_ALLOWSHUTDOWN               1006
#define IDC_APPLY                       1007
#define IDC_ATT                         1008
#define IDC_AUTOCAPT1                   1009
#define IDC_AUTOCAPT2                   1010
#define IDC_AUTOCAPT3                   1011
#define IDC_AUTO_DISPLAY_NO             1012
#define IDC_BLANK                       1013
#define IDC_BLANK2                      1014
#define IDC_BLANKINGTXT                 1015
#define IDC_BUILDTEXT                   1016
#define IDC_BUILDTIME                   1017
#define IDC_BUTTON1                     1018
#define IDC_BUTTON_EXPAND               1019
#define IDC_CAPTION_STATIC              1020
#define IDC_CHATAREA_EDIT               1021
#define IDC_CHECK1                      1022
#define IDC_CHECK2                      1023
#define IDC_CHECK3                      1024
#define IDC_CHECK4                      1025
#define IDC_CHECK5                      1026
#define IDC_CHECK6                      1027
#define IDC_CHECK7                      1028
#define IDC_CHECK8                      1029
#define IDC_CHECK9                      1030
#define IDC_CHECKCLOUD                  1031
#define IDC_CHECKDRIVER                 1032
#define IDC_CHECKG1D                    1033
#define IDC_CHECKG1L                    1034
#define IDC_CHECKG2D                    1035
#define IDC_CHECKG2L                    1036
#define IDC_CHECKG3D                    1037
#define IDC_CHECKG3L                    1038
#define IDC_CLEAR                       1039
#define IDC_CLEAR_B                     1040
#define IDC_CLIENTTEXT                  1041
#define IDC_CLOSE                       1042
#define IDC_CLOUDCODE                   1043
#define IDC_CLOUDSERVER                 1044
#define IDC_CLOUDSTATUS                 1045
#define IDC_COLLABO                     1046
#define IDC_COMBO1                      1047
#define IDC_CONNECT                     1048
#define IDC_CONNECTION_NUMBER_LABEL     1049
#define IDC_CONNECTION_NUMBER_STATIC    1050
#define IDC_CONNECT_BORDER              1051
#define IDC_CONNECT_CORBA               1052
#define IDC_CONNECT_HTTP                1053
#define IDC_CONNECT_SOCK                1054
#define IDC_CONNECT_XDMCP               1055
#define IDC_CONNSETTINGS_BORDER         1056
#define IDC_CONSOLE_ONLY                1057
#define IDC_COPYRIGHT                   1058
#define IDC_CURSOR1                     1059
#define IDC_CURSOR2                     1060
#define IDC_CURSOR3                     1061
#define IDC_CURSOR4                     1062
#define IDC_CURSOR6                     1063
#define IDC_CURSOR7                     1064
#define IDC_CURSOR8                     1065
#define IDC_CURSOR9                     1066
#define IDC_CURSORBLANK                 1067
#define IDC_DACCEPT                     1068
#define IDC_DEFAULTBOX                  1069
#define IDC_DISABLETRAY                 1070
#define IDC_DISABLE_INPUTS              1071
#define IDC_DISABLE_LOCAL_INPUTS        1072
#define IDC_DISPLAYNO                   1073
#define IDC_DISPLAY_NO_LABEL            1074
#define IDC_DISPLAY_NUMBER              1075
#define IDC_DREFUSE                     1076
#define IDC_DRIVER                      1077
#define IDC_EDIT1                       1078
#define IDC_EDIT2                       1079
#define IDC_EDIT3                       1080
#define IDC_EDITQUERYTEXT               1081
#define IDC_EDITQUERYYEXT               1082
#define IDC_EDIT_PATH                   1083
#define IDC_EMAIL                       1084
#define IDC_EURO                        1085
#define IDC_EXTERNALIPADDRESS           1086
#define IDC_FILETRANSFER                1087
#define IDC_FINGER                      1088
#define IDC_FRAME                       1089
#define IDC_FTUSERIMPERSONATION_CHECK   1090
#define IDC_GAMMAGRAY                   1091
#define IDC_GREEN                       1092
#define IDC_GROUP1                      1093
#define IDC_GROUP2                      1094
#define IDC_GROUP3                      1095
#define IDC_HELPWEB                     1096
#define IDC_HIDE_B                      1097
#define IDC_HOOK                        1098
#define IDC_HOSTNAME_EDIT               1099
#define IDC_HOSTNAME_STATIC             1100
#define IDC_HOSTS                       1101
#define IDC_HOST_ADD                    1102
#define IDC_HOST_DOWN                   1103
#define IDC_HOST_EDIT                   1104
#define IDC_HOST_REMOVE                 1105
#define IDC_HOST_UP                     1106
#define IDC_IDCODE                      1107
#define IDC_INPUTAREA_EDIT              1108
#define IDC_IPV6                        1109
#define IDC_JAP_INPUTS                  1110
#define IDC_KILL_B                      1111
#define IDC_LIST                        1112
#define IDC_LOCALTEXT_EDIT              1113
#define IDC_LOCKSETTINGS                1114
#define IDC_LOCKSETTING_LOCK            1115
#define IDC_LOCKSETTING_LOGOFF          1116
#define IDC_LOCKSETTING_NOTHING         1117
#define IDC_LOG                         1118
#define IDC_LOGO                        1119
#define IDC_LOOPBACKONLY                1120
#define IDC_MANUAL_DISPLAY_NO           1121
#define IDC_MAXCPU                      1122
#define IDC_MAXDISCONNECT               1123
#define IDC_MAXREFUSE                   1124
#define IDC_MAXVIEWERS                  1125
#define IDC_MSLOGON                     1126
#define IDC_MSLOGON_CHECK               1127
#define IDC_MSLOGON_CHECKD              1128
#define IDC_MSLOGON_CHECKD2             1129
#define IDC_MV1                         1130
#define IDC_MV2                         1131
#define IDC_MV3                         1132
#define IDC_MV4                         1133
#define IDC_NAME                        1134
#define IDC_NAME_APPLI                  1135
#define IDC_NEW_MSLOGON                 1136
#define IDC_NOSCREENSAVER               1137
#define IDC_NOTE_STATIC                 1138
#define IDC_NOTIFOCATION                1139
#define IDC_ONEVENT_ONLY                1140
#define IDC_OSD                         1141
#define IDC_PASSWD_EDIT                 1142
#define IDC_PASSWORD                    1143
#define IDC_PASSWORD2                   1144
#define IDC_PASSWORD_LABEL              1145
#define IDC_PASSWORD_LABEL2             1146
#define IDC_PATH                        1147
#define IDC_PENDING_LISTBOX             1148
#define IDC_PERSISTENT_CHECK            1149
#define IDC_PLUGINS_COMBO               1150
#define IDC_PLUGIN_BUTTON               1151
#define IDC_PLUGIN_CHECK                1152
#define IDC_POLL_FOREGROUND             1153
#define IDC_POLL_FOREGROUND2            1154
#define IDC_POLL_FULLSCREEN             1155
#define IDC_POLL_UNDER_CURSOR           1156
#define IDC_PORTHTTP                    1157
#define IDC_PORTNO                      1158
#define IDC_PORTNO_AUTO                 1159
#define IDC_PORTNO_LABEL                1160
#define IDC_PORTRFB                     1161
#define IDC_Path1                       1162
#define IDC_Path2                       1163
#define IDC_Path3                       1164
#define IDC_QUERYDISABLETIME            1165
#define IDC_RADIO1                      1166
#define IDC_RADIO2                      1167
#define IDC_RADIO3                      1168
#define IDC_RADIO4                      1169
#define IDC_RADIO6                      1170
#define IDC_RADIONOTIFICATIONIFPROVIDED 1171
#define IDC_RADIONOTIFICATIONON         1172
#define IDC_RDPMODE                     1173
#define IDC_RED                         1174
#define IDC_REMOTETEXT_EDIT             1175
#define IDC_REMOVE_Aero                 1176
#define IDC_REMOVE_WALLPAPER            1177
#define IDC_REVERSEAUTH                 1178
#define IDC_SAVEPASSWORDSECURE          1179
#define IDC_SCALE                       1180
#define IDC_SCEXPAND                    1181
#define IDC_SEND_B                      1182
#define IDC_SERVICE_COMMANDLINE         1183
#define IDC_SETMASTER                   1184
#define IDC_SHOWOPTIONS                 1185
#define IDC_SINGLE_WINDOW               1186
#define IDC_SLIDERFPS                   1187
#define IDC_SPECDISPLAY                 1188
#define IDC_SPECPORT                    1189
#define IDC_STARTCLOUD                  1190
#define IDC_STARTREP                    1191
#define IDC_STATICELEVATED              1192
#define IDC_STATICFPS                   1193
#define IDC_STATICFPS5                  1194
#define IDC_STATICFPS60                 1195
#define IDC_STATICIDCODE                1196
#define IDC_STATIC_SPLIT                1197
#define IDC_STATIC_TEXT                 1198
#define IDC_STATIC_TEXT1                1199
#define IDC_STATUS                      1200
#define IDC_TEXTBOTTOM                  1201
#define IDC_TEXTCHAT_B                  1202
#define IDC_TEXTMIDDLE                  1203
#define IDC_TEXTRICHTTOP                1204
#define IDC_TEXTRIGHTBOTTOM             1205
#define IDC_TEXTRIGHTMIDDLE             1206
#define IDC_TEXTTOP                     1207
#define IDC_TITLEWINDOW                 1208
#define IDC_TRADEMARK                   1209
#define IDC_TURBOMODE                   1210
#define IDC_UNICODE_INPUTS              1211
#define IDC_UPDATE_BORDER               1212
#define IDC_VERSION                     1213
#define IDC_VIDEO                       1214
#define IDC_VIEWERS_LISTBOX             1215
#define IDC_VIEWERS_LISTBOX2            1216
#define IDC_VIRTUAL                     1217
#define IDC_VNC                         1218
#define IDC_VNCLOGO                     1219
#define IDC_WARNING                     1220
#define IDC_WIN8_HELPER                 1221
#define IDC_WWW                         1222
#define IDC_WWW2                        1223
#define IDC_WWW3                        1224
#define IDC_YELLOW                      1225
#define IDE_CUSTOM1                     4377
#define ID_ABOUT                        32771
#define ID_ADMIN_PROPERTIES             32772
#define ID_ANOTHER_INST                 32773
#define ID_AUTHAD_NOT_FO                32774
#define ID_AUTH_NOT_FO                  32775
#define ID_AUTOACCEPT_U                 32776
#define ID_AUTOREJECT_U                 32777
#define ID_CADERROR                     32778
#define ID_CADERRORFILE                 32779
#define ID_CADPERMISSION                32780
#define ID_CANNOT_EDIT_DEFAULT_PREFS    32781
#define ID_CHAT_WITH_S_ULTRAVNC         32782
#define ID_CLOSE                        32783
#define ID_CLOSE_SERVICE                32784
#define ID_CURRENT_USER_PROP            32785
#define ID_DEFAULT_PROPERTIES           32786
#define ID_DEFAULT_SYST_PROP            32787
#define ID_DESKTOP_BITBLT_MEM           32788
#define ID_DESKTOP_BITBLT_ROOT          32789
#define ID_DESKTOP_PLANAR_NOTC          32790
#define ID_FAILED_CONNECT_LISTING_VIEW  32791
#define ID_FAILED_INIT                  32792
#define ID_HOME                         32793
#define ID_KILLCLIENTS                  32794
#define ID_LISTCLIENTS                  32795
#define ID_MB1                          32796
#define ID_MENU_CLOUDCONNECT            32797
#define ID_NO_CURRENT_USER_ERR          32798
#define ID_NO_EXIST_INST                32799
#define ID_NO_OVERRIDE_ERR              32800
#define ID_NO_PASSWD_NO_LOGON_WARN      32801
#define ID_NO_PASSWD_NO_OVERRIDE_ERR    32802
#define ID_NO_PASSWD_NO_OVERRIDE_WARN   32803
#define ID_NO_PASSWORD_WARN             32804
#define ID_NO_PLUGIN_DETECT             32805
#define ID_ONLINEHELP                   32806
#define ID_OUTGOING_CONN                32807
#define ID_OUTGOING_CONNECTION          32808
#define ID_PLUGIN_LOADIN                32809
#define ID_PLUGIN_NOT_LOAD              32810
#define ID_PROPERTIES                   32811
#define ID_REBOOTSAFEMODE               32812
#define ID_REBOOT_FORCE                 32813
#define ID_RICHED32_DLL_LD              32814
#define ID_RICHED32_UNLOAD              32815
#define ID_RUNASSERVICE                 32816
#define ID_SCM_NOT_HERE                 32817
#define ID_SERVHELP_NREM                32818
#define ID_SERVHELP_UNAB                32819
#define ID_SERV_CT_MISS                 32820
#define ID_SERV_CT_UNREG                32821
#define ID_SERV_FAIL_ST                 32822
#define ID_SERV_MK_UNREG                32823
#define ID_SERV_NCONTACT                32824
#define ID_SERV_NOT_REG                 32825
#define ID_SERV_NOT_STOP                32826
#define ID_SERV_NOT_UNRG                32827
#define ID_SERV_NT_FOUND                32828
#define ID_SERV_OLD_REG                 32829
#define ID_SERV_SUCCESS_INST            32830
#define ID_SERV_SUCCESS_REG             32831
#define ID_SERV_SUCCESS_UNREG           32832
#define ID_START_SERVICE                32833
#define ID_TRAY_CLOUDCONNECT            32834
#define ID_TRAY_DELETESOFTWARECAD       32835
#define ID_TRAY_ENABLESOFTWARECAD       32836
#define ID_TRAY_FORCEREBOOT             32837
#define ID_TRAY_REBOOTINSAFEMODE        32838
#define ID_TRAY_VISITUSONLINE           32839
#define ID_ULTRAVNC_TEXTCHAT            32840
#define ID_ULTRAVNC_WARNING             32841
#define ID_UNABLE_INST                  32842
#define ID_UNABLE_PROC_MSLOGON          32843
#define ID_UNINSTALL_SERVICE            32844
#define ID_VISITUSONLINE_FACEBOOK       32845
#define ID_VISITUSONLINE_FORUM          32846
#define ID_VISITUSONLINE_GITHUB         32847
#define ID_VISITUSONLINE_HOMEPAGE       32848
#define ID_VISITUSONLINE_MASTODON       32849
#define ID_VISITUSONLINE_OPENHUB        32850
#define ID_VISITUSONLINE_REDDIT         32851
#define ID_VISITUSONLINE_XTWITTER       32852
#define ID_WARNING                      32853
#define ID_WINVNC_ERROR                 32854
#define ID_WINVNC_USAGE                 32855
#define ID_WINVNC_WARNIN                32856
#define ID_WVNC                         32857

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32858
#define _APS_NEXT_CONTROL_VALUE         1226
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
